apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clickcount-deploy
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: clickcount
        role: frontend
    spec:
      containers:
      - name: clickcount
        image: {{ frontend_image }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
          - name: web
            containerPort: 8080
        env:
          - name: CUSTOM_REDIS_HOST
            value: clickcount-redis