apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: redis
      labels:
        app: clickcount
        role: database
    spec:
      containers:
      - name: redis
        image: redis
        command: [ "redis-server" ]
        args: [ "--appendonly", "yes" ]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: redis
          containerPort: 6379
        volumeMounts:
            - mountPath: /data
              name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-vol-claim
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  namespace: ci
  name: redis-vol-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "std"
spec:
  "accessModes":
   - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"