---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: clickcount
    role: database

---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-service
  labels:
    app: clickcount
    role: frontend
    dns: route53
  annotations:
    domainName: "{{ namespace }}.k8s.uo.techx.fr"
spec:
  type: "LoadBalancer"
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: clickcount
    role: frontend
