---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
    app: clickcount
    role: database

---
apiVersion: v1
kind: Service
metadata:
  name: clickcount-service
  labels:
    app: clickcount
    dns: route53
  annotations:
    domainName: {{ namespace }}.k8s.uo.techx.fr
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: clickcount
    role: frontend
